# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Watson Memorials | Headstones Memorials and Gravestones
email: contact@watsonmemorials.co.uk
description: "Darlington based Monumental Mason providing Headstone, Memorial and Gravestone services across County Durham and North Yorkshire."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://watsonmemorials.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: watsonmemorials
facebook_pagename: watsonmemorials
linkedin_companypage: watsonmemorials

# Build settings
sass:
    sass_dir: _sass
    style: compressed

markdown: kramdown

page_gen-dirs: true

page_gen:
  - data: lawn-memorials
    template: memorial
    dir: new-memorials/memorials
    index_files: false
    name: name
    name_expr: record['name'].downcase
    title: name
  - data: churchyard-memorials
    template: memorial
    dir: new-memorials/memorials
    index_files: false
    name: name
    name_expr: record['name'].downcase
    title: name
  - data: childrens-memorials
    template: memorial
    dir: new-memorials/memorials
    index_files: false
    name: name
    name_expr: record['name'].downcase
    title: name
  - data: vases
    template: memorial
    dir: new-memorials/memorials
    index_files: false
    name: name
    name_expr: record['name'].downcase
    title: name
  - data: plaques
    template: memorial
    dir: new-memorials/memorials
    index_files: false
    name: name
    name_expr: record['name'].downcase
    title: name
  - data: kerbs
    template: memorial
    dir: new-memorials/memorials
    index_files: false
    name: name
    name_expr: record['name'].downcase
    title: name

excerpt_separator: <!--more-->

gems:
  - jekyll-feed
  - jekyll-tidy

url: "https://watsonmemorials.co.uk"

plugins_dir:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - _sass
  - _scss
  - .sass-cache
  - docs
  - .gitignore
  - node_modules
  - gruntfile
  - package
  - package-lock

destination: docs
